#COMMON
log_path: "./logs/logs.json"
sqlite_path: "./storage/sqlite_db"
db_type: "postgresql"

#PG
POSTGRES_USER: "truckgodbuser"
POSTGRES_PASSWORD: "6085dc189f1444975fc8e832a2bb07c3d0816212"
#pg_auth
POSTGRES_DB_AUTH: "truckgodb_auth"
POSTGRES_PORT_AUTH: "5437"
#pg_user
POSTGRES_DB_USER: "truckgodb_user"
POSTGRES_PORT_USER: "8881"
#pg_order
POSTGRES_DB_ORDER: "truckgodb_order"
POSTGRES_PORT_ORDER: "8882"
#pg_payment
POSTGRES_DB_PAYMENT: "truckgodb_payment"
POSTGRES_PORT_PAYMENT: "8883"
#pg_shipping
POSTGRES_DB_SHIPPING: "truckgodb_shipping"
POSTGRES_PORT_SHIPPING: "8883"

#GRPC
#grpc_auth
GRPC_PORT_AUTH: "50047"
#grpc_user
GRPC_PORT_USER: "50048"
#grpc_order
GRPC_PORT_ORDER: "50049"
#grpc_payment
GRPC_PORT_PAYMENT: "50050"
#grpc_shipping
GRPC_PORT_SHIPPING: "50051"