#COMMON
log_path: "./logs/logs.json"
log_level: "debug"
sqlite_path: "./storage/sqlite_db"
db_type: "postgresql"
env_path: "./.env"
#JWT_SECRET: "TruckGoProjector"

#PG
POSTGRES_USER: "truckgodbuser"
POSTGRES_PASSWORD: "6085dc189f1444975fc8e832a2bb07c3d0816212"
#pg_auth
#POSTGRES_DB_AUTH: "truckgodb_auth"
#pg_user
POSTGRES_DB_USER: "truckgodb_user"
#pg_order
POSTGRES_DB_ORDER: "truckgodb_order"
#pg_payment
POSTGRES_DB_PAYMENT: "truckgodb_payment"
#pg_shipping
POSTGRES_DB_SHIPPING: "truckgodb_shipping"

#GRPC
#grpc_auth
#GRPC_PORT_AUTH: "50047"
#grpc_user
GRPC_PORT_USER: "50048"
#grpc_order
GRPC_PORT_ORDER: "50049"
#grpc_payment
GRPC_PORT_PAYMENT: "50050"
#grpc_shipping
GRPC_PORT_SHIPPING: "50051"

#ROUTES
MAP_API_KEY: "5b3ce3597851110001cf62484ac69c5d6ebf4d3ab937dd36721941a9"
START_PRICE: "70"
KM_PRICE: "10"