services:
  db_auth:
    image: postgres:16
    container_name: pg_truckgo_auth
    environment:
      POSTGRES_USER: truckgodbuser
      POSTGRES_PASSWORD: 6085dc189f1444975fc8e832a2bb07c3d0816212
      POSTGRES_DB: truckgodb_auth
    ports:
      - "8880:5432"
    volumes:
      - postgres_auth:/var/lib/postgresql/data
  db_orders:
    image: postgres:16
    container_name: pg_truckgo_orders
    environment:
      POSTGRES_USER: truckgodbuser
      POSTGRES_PASSWORD: 6085dc189f1444975fc8e832a2bb07c3d0816212
      POSTGRES_DB: truckgodb_orders
    ports:
      - "8881:5432"
    volumes:
      - postgres_orders:/var/lib/postgresql/data
  db_payments:
      image: postgres:16
      container_name: pg_truckgo_payments
      environment:
        POSTGRES_USER: truckgodbuser
        POSTGRES_PASSWORD: 6085dc189f1444975fc8e832a2bb07c3d0816212
        POSTGRES_DB: truckgodb_payments
      ports:
        - "8882:5432"
      volumes:
        - postgres_payments:/var/lib/postgresql/data
  db_shippings:
      image: postgres:16
      container_name: pg_truckgo_shippings
      environment:
        POSTGRES_USER: truckgodbuser
        POSTGRES_PASSWORD: 6085dc189f1444975fc8e832a2bb07c3d0816212
        POSTGRES_DB: truckgodb_shippings
      ports:
        - "8883:5432"
      volumes:
        - postgres_shippings:/var/lib/postgresql/data

volumes:
  postgres_auth:
  postgres_orders:
  postgres_payments:
  postgres_shippings:

