services:

  db_auth:
      image: postgres:16
      container_name: pg_truckgo_auth
      depends_on:
        - db_user
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB_AUTH}
      ports:
        - "${DB_AUTH_PORT}:5432"
      restart: always
      volumes:
        - postgres_auth:/var/lib/postgresql/data
      networks:
        app-network:
            ipv4_address: 172.0.0.2

  grpc-auth:
      image: golang:1.23-alpine
      container_name: grpcapi-auth
      depends_on:
        - db_auth
      working_dir: /app
      volumes:
        - ./go.mod:/app/go.mod
        - ./go.sum:/app/go.sum
        - ./auth:/app/auth
        - ./user:/app/user
        - ./shared:/app/shared
        - ./config.yaml:/app/config.yaml
        - ./.env:/app/.env
        - ./logs:/app/logs
      networks:
        app-network:
            ipv4_address: 172.0.0.3
      ports:
        - "${GRPC_PORT_AUTH}:${GRPC_PORT_AUTH}"
      command: ["/bin/sh", "-c", "go build -o /app/auth/server /app/auth/cmd/main.go && chmod +x /app/auth/server && /app/auth/server"]

  db_user:
      image: postgres:16
      container_name: pg_truckgo_user
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB_USER}
      ports:
        - "${DB_USER_PORT}:5432"
      restart: always
      volumes:
        - postgres_user:/var/lib/postgresql/data
      networks:
        app-network:
            ipv4_address: 172.0.0.4

  db_order:
      image: postgres:16
      container_name: pg_truckgo_order
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB_ORDER}
      ports:
        - "${DB_ORDER_PORT}:5432"
      restart: always
      healthcheck:
        test: ["CMD-SHELL", "pg_isready"]
        interval: 5s
        timeout: 5s
        retries: 5
      volumes:
        - postgres_order:/var/lib/postgresql/data
      networks:
        app-network:
            ipv4_address: 172.0.0.5

  db_payment:
      image: postgres:16
      container_name: pg_truckgo_payment
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB_PAYMENT}
      ports:
        - "${DB_PAYMENT_PORT}:5432"
      restart: always
      healthcheck:
        test: ["CMD-SHELL", "pg_isready"]
        interval: 5s
        timeout: 5s
        retries: 5
      volumes:
        - postgres_payment:/var/lib/postgresql/data
      networks:
        app-network:
            ipv4_address: 172.0.0.6

  db_shipping:
      image: postgres:16
      container_name: pg_truckgo_shippings
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB_SHIPPING}
      ports:
        - "${DB_SHIPPING_PORT}:5432"
      restart: always
      healthcheck:
        test: ["CMD-SHELL", "pg_isready"]
        interval: 5s
        timeout: 5s
        retries: 5
      volumes:
        - postgres_shipping:/var/lib/postgresql/data
      networks:
        app-network:
            ipv4_address: 172.0.0.7

  shippings:
      container_name: truckgo_shippings_server
      build:
        context: .
        dockerfile: ./DockerfileShippings
      depends_on:
        db_shipping:
          condition: service_healthy
      ports:
        - "50051:50051"
      restart: always
      volumes:
        - ./config.yaml:/app/config.yaml
        - ./.env:/app/.env
        - ./logs:/app/logs
      networks:
        app-network:
            ipv4_address: 172.0.0.8

  orders:
      container_name: truckgo_orders_server
      build:
        context: .
        dockerfile: ./DockerfileOrders
      depends_on:
        db_order:
          condition: service_healthy
      ports:
        - "50049:50049"
      volumes:
        - ./config.yaml:/app/config.yaml
        - ./.env:/app/.env
        - ./logs:/app/logs
      restart: always
      networks:
        app-network:
            ipv4_address: 172.0.0.9

  users:
      container_name: truckgo_users_server
      build:
        context: .
        dockerfile: ./DockerfileUsers
      depends_on:
        db_shipping:
          condition: service_healthy
      ports:
        - "50048:50048"
      volumes:
        - ./config.yaml:/app/config.yaml
        - ./.env:/app/.env
        - ./logs:/app/logs
      restart: always
      networks:
        app-network:
            ipv4_address: 172.0.0.10

  payment:
    container_name: truckgo_payment_server
    build:
      context: .
      dockerfile: ./DockerfilePayment
    depends_on:
      db_payment:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    ports:
      - "50050:50050"
    restart: always
    networks:
      app-network:
        ipv4_address: 172.0.0.11

volumes:
  postgres_auth:
  postgres_user:
  postgres_order:
  postgres_payment:
  postgres_shipping:

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.0.0.0/16