services:

  db_auth:
    image: postgres:16
    container_name: pg_truckgo_auth
    environment:
      POSTGRES_USER: truckgodbuser
      POSTGRES_PASSWORD: 6085dc189f1444975fc8e832a2bb07c3d0816212
      POSTGRES_DB: truckgodb_auth
    ports:
      - "8880:5432"
    restart: always
    volumes:
      - postgres_auth:/var/lib/postgresql/data

  db_user:
    image: postgres:16
    container_name: pg_truckgo_user
    environment:
      POSTGRES_USER: truckgodbuser
      POSTGRES_PASSWORD: 6085dc189f1444975fc8e832a2bb07c3d0816212
      POSTGRES_DB: truckgodb_user
    ports:
      - "8881:5432"
    restart: always
    volumes:
      - postgres_user:/var/lib/postgresql/data

  db_order:
    image: postgres:16
    container_name: pg_truckgo_order
    environment:
      POSTGRES_USER: truckgodbuser
      POSTGRES_PASSWORD: 6085dc189f1444975fc8e832a2bb07c3d0816212
      POSTGRES_DB: truckgodb_order
    ports:
      - "8882:5432"
    restart: always
    volumes:
      - postgres_order:/var/lib/postgresql/data

  db_payment:
      image: postgres:16
      container_name: pg_truckgo_payment
      environment:
        POSTGRES_USER: truckgodbuser
        POSTGRES_PASSWORD: 6085dc189f1444975fc8e832a2bb07c3d0816212
        POSTGRES_DB: truckgodb_payment
      ports:
        - "8883:5432"
      restart: always
      volumes:
        - postgres_payment:/var/lib/postgresql/data

  db_shipping:
      image: postgres:16
      container_name: pg_truckgo_shippings
      environment:
        POSTGRES_USER: truckgodbuser
        POSTGRES_PASSWORD: 6085dc189f1444975fc8e832a2bb07c3d0816212
        POSTGRES_DB: truckgodb_shipping
      ports:
        - "8884:5432"
      restart: always
      volumes:
        - postgres_shipping:/var/lib/postgresql/data

  shippings:
      container_name: truckgo_shippings_server
      build:
        context: .
        dockerfile: ./shipping-service/Dockerfile
      ports:
        - "50051:50051"
      restart: always
      networks:
        - app-network

volumes:
  postgres_auth:
  postgres_user:
  postgres_order:
  postgres_payment:
  postgres_shipping:

networks:
  app-network:
    driver: bridge