name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GO_VERSION: "1.23"
  GOLANGCI_LINT_VERSION: "v1.61.0"

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code from the repo
        uses: actions/checkout@v4

      - name: Set up Go environment
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Ensure Go Modules are tidy
        run: go mod tidy && git diff --exit-code go.mod go.sum || (echo "Go Modules are not tidy" && exit 1)

      - name: Check generated code
        run: |
          go generate ./... && git diff --exit-code || (echo "Generated code has changes" && exit 1)

      - name: Compile code
        run: |
          go build ./...

      - name: Lint Go code with golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}

      - name: Run tests
        run: |
          go test -race -count=1 -shuffle=on ./...
